<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Socket" Id="{3ea1f794-102b-4ade-8899-710f8bdc81c0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Socket
VAR
	fbFRSocket:fb_socket_FR;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFRSocket();]]></ST>
    </Implementation>
    <LineIds Name="Socket">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>